spring:
  application:
    name: my-server

  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://localhost:3306/sky-delivery
    username: root
    password: ${z.y.password}


  redis:
    database: ${spring-redis-pro.database}
    host: ${spring-redis-pro.host}
    port: ${spring-redis-pro.port}
    password: ${spring-redis-pro.password}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-prod.client-id}
            client-secret: ${google-prod.client-secret}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: ${google-prod.authorization-uri}
            token-uri: ${google-prod.token-uri}
            user-info-uri: ${google-prod.user-info-uri}
            user-name-attribute: ${google-prod.user-name-attribute}



mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  #mybatis 接受result开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true



aws-config:
  accessKey: ${aws-config-pro.accessKey}
  secretKey: ${aws-config-pro.secretKey}
  bucketName: ${aws-config-pro.bucketName}
  region: ${aws-config-pro.region}


